name: Trigger auto deployment for java-springboot

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/java-springboot-AutoDeployTrigger-0b4b53da-2edf-4cd0-95d7-5858914c573b.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.JAVASPRINGBOOT_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.JAVASPRINGBOOT_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.JAVASPRINGBOOT_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: docker.io
          registryUsername: ${{ secrets.JAVASPRINGBOOT_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.JAVASPRINGBOOT_REGISTRY_PASSWORD }}
          containerAppName: java-springboot
          resourceGroup: eazysticker
          imageToBuild: santhoshkumarpv00@gmail.com/java-springboot:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


